<h1><?= __('Our Restaurants') ?></h1>
<?php $viewModel = $block->getViewModelRestaurantsdata(); ?>
<?php if (is_object($viewModel)): ?>
    <?php foreach ($viewModel->getRestaurants() as $restaurant): ?>
        <?php if ($restaurant->getName()): ?>
            <p><?= __('Name') ?></p>
            <p><b><?= $restaurant->getName() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getCapacity()): ?>
            <p><?= __('Capacity') ?></p>
            <p><b><?= $restaurant->getCapacity() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getLocation()): ?>
            <p><?= __('Location') ?></p>
            <p><b><?= $restaurant->getLocation() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getCreatedAt()): ?>
            <p><?= __('Created at') ?></p>
            <p><b><?= $restaurant->getCreatedAt() ?></b></p>
        <?php endif; ?>
        <p>
            <a href="<?= $block->getUrl('restaurants/restaurant/edit', ['id' => $restaurant->getId()]) ?>">
            <?= __('Edit') ?>
            </a>
        </p>
        <p>
            <a href="<?= $block->getUrl('restaurants/restaurant/delete', ['id' => $restaurant->getId()]) ?>">
                <?= __('Delete') ?>
            </a>
        </p>
    -------------------------------------------------------
    <?php endforeach; ?>
    <p>
        <a href="<?= $block->getUrl('restaurants/restaurant/create') ?>"><?= __('Create a new restaurant') ?></a>
    </p>

    <?php if ($viewModel->showPaging()): ?>
        <div class="paging">
            <a href="?p=<?= $viewModel->getPrevPage();  ?>"><?= __('Prev page') ?></a>
            <a href="?p=<?= $viewModel->getNextPage(); ?>"><?= __('Next page') ?></a>
        </div>
    <?php endif; ?>


<?php endif;?>
